name: Flutter CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Cache Flutter SDK
      uses: actions/cache@v3
      with:
        path: ~/.pub-cache
        key: flutter-${{ runner.os }}-${{ hashFiles('pubspec.yaml') }}
        restore-keys: |
          flutter-${{ runner.os }}-

    - name: Install Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.10.5' 

    - name: Install dependencies
      run: flutter pub get

    - name: Cache build
      uses: actions/cache@v3
      with:
        path: build
        key: build-${{ runner.os }}-${{ hashFiles('pubspec.yaml') }}
        restore-keys: |
          build-${{ runner.os }}-
