name: Flutter CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: frontend

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Cache Flutter SDK
      uses: actions/cache@v3
      with:
        path: ~/.pub-cache
        key: flutter-${{ runner.os }}-${{ hashFiles('frontend/pubspec.yaml') }}
        restore-keys: |
          flutter-${{ runner.os }}-

    - name: Install Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.3'
        
    - name: List Directory Contents
      run: ls -R
      
    - name: Install dependencies
      run: flutter pub get
      
    - name: Cache build
      uses: actions/cache@v3
      with:
        path: frontend/build
        key: build-${{ runner.os }}-${{ hashFiles('frontend/pubspec.yaml') }}
        restore-keys: |
          build-${{ runner.os }}-
          
    - name: Run tests
      run: flutter test
